version: "3.7"

services:
  example:
    container_name: tour-of-heroes
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "4201:4200"
